NANOSECONDS = 1
MICROSECONDS = 1000 * NANOSECONDS
MILLISCONDS = 1000 * MICROSECONDS
SECONDS = 1000 * MILLISCONDS


MINE_RATE = 2 * SECONDS

DEFAULT_BALANCE = 1000

MINING_REWARD = 50
MINING_REWARD_INPUT = {"address": "*--officical_mining_reward--*"}
