class TransactionPool:
    def __init__(self):
        self.transaction_map = {}

    def set_transaction(self, transaction):
        self.transaction_map[transaction.id] = transaction

    def transaction_already_exist(self, address):
        """
        Find a transaction generated by the address in the transaction bool.
        """
        for transaction in self.transaction_map.values():
            if transaction.input["address"] == address:
                return transaction
