class TransactionPool:
    def __init__(self):
        self.transaction_map = {}

    def set_transaction(self, transaction):
        self.transaction_map[transaction.id] = transaction

    def transaction_already_exist(self, address):
        """
        Find a transaction generated by the address in the transaction bool.
        """
        for transaction in self.transaction_map.values():
            if transaction.input["address"] == address:
                return transaction

    def transaction_data(self):
        """
        Return the transaction of the transaction pool
        represented in the json serialized format
        """
        transaction_values = self.transaction_map.values()
        transaction_data = list(
            map(lambda transaction: transaction.to_json(), transaction_values)
        )

        return transaction_data

    def clear_blockchain_transactions(self, blockchain):
        """
        Delete blockchain recorded transactions from the transaction pool.
        """
        for block in blockchain.chain:
            for transaction in block.data:
                try:
                    del self.transaction_map[transaction["id"]]

                except KeyError:
                    pass
